"""add sexo a modelo Students

Revision ID: 0911f2b409d9
Revises: 4e5ef9496722
Create Date: 2025-11-27 00:42:44.094580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0911f2b409d9'
down_revision = '4e5ef9496722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('sexo')

    # ### end Alembic commands ###
