"""add predicction fields to Student

Revision ID: 4e5ef9496722
Revises: 7878e3db1863
Create Date: 2025-11-26 23:15:06.013100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5ef9496722'
down_revision = '7878e3db1863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_carrera', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tiempo_estudio', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ausencias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cinco_f', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aplazos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('promedio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('promedio')
        batch_op.drop_column('aplazos')
        batch_op.drop_column('cinco_f')
        batch_op.drop_column('ausencias')
        batch_op.drop_column('tiempo_estudio')
        batch_op.drop_column('estado_carrera')

    # ### end Alembic commands ###
