"""Add apellido and cedula to students

Revision ID: 7878e3db1863
Revises: c7dcb29f1a4e
Create Date: 2025-11-26 20:32:28.373695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7878e3db1863'
down_revision = 'c7dcb29f1a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('cedula', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['cedula'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cedula')
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###
