"""add sexo a modelo Students

Revision ID: 873a385d3e43
Revises: 0911f2b409d9
Create Date: 2025-11-27 01:22:42.412482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873a385d3e43'
down_revision = '0911f2b409d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
